### ISSUE TITLE
Media recording crash on Rene's device

### ISSUE THREAD

**Issue by tpetmanson** [SmileMeBack/smilemeback#13]
During releasing the Record sound button, following crash appears:

06-21 16:30:16.176  28805-28805/com.smilemeback E/MediaRecorder﹕ stop failed: -1007
06-21 16:30:16.176  28805-28805/com.smilemeback E/InputEventReceiver﹕ Exception dispatching input event.
06-21 16:30:16.176  28805-28805/com.smilemeback E/MessageQueue-JNI﹕ Exception in MessageQueue callback: handleReceiveCallback
06-21 16:30:16.216  28805-28805/com.smilemeback E/MessageQueue-JNI﹕ java.lang.RuntimeException: stop failed.
            at android.media.MediaRecorder.stop(Native Method)
            at com.smilemeback.activities.screens.AddAudioScreen.stopRecording(AddAudioScreen.java:196)
            at com.smilemeback.activities.screens.AddAudioScreen.onRecord(AddAudioScreen.java:148)
            at com.smilemeback.activities.screens.AddAudioScreen.access$200(AddAudioScreen.java:45)
            at com.smilemeback.activities.screens.AddAudioScreen$1.onTouch(AddAudioScreen.java:85)
            at android.view.View.dispatchTouchEvent(View.java:7663)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2284)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1578)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2468)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2232)
            at android.view.View.dispatchPointerEvent(View.java:7875)
            at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3898)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3782)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5034)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5013)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5111)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java:125)
            at android.os.Looper.loop(Looper.java:124)
            at android.app.ActivityThread.main(ActivityThread.java:5283)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
            at dalvik.system.NativeStart.main(Native Method)
06-21 16:30:16.216  28805-28805/com.smilemeback D/AndroidRuntime﹕ Shutting down VM
06-21 16:30:16.216  28805-28805/com.smilemeback W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41881960)
06-21 16:30:16.236  28805-28805/com.smilemeback E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: stop failed.
            at android.media.MediaRecorder.stop(Native Method)
            at com.smilemeback.activities.screens.AddAudioScreen.stopRecording(AddAudioScreen.java:196)
            at com.smilemeback.activities.screens.AddAudioScreen.onRecord(AddAudioScreen.java:148)
            at com.smilemeback.activities.screens.AddAudioScreen.access$200(AddAudioScreen.java:45)
            at com.smilemeback.activities.screens.AddAudioScreen$1.onTouch(AddAudioScreen.java:85)
            at android.view.View.dispatchTouchEvent(View.java:7663)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2284)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1578)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2468)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2232)
            at android.view.View.dispatchPointerEvent(View.java:7875)
            at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3898)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3782)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5034)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5013)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5111)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java:125)
            at android.os.Looper.loop(Looper.java:124)
            at android.app.ActivityThread.main(ActivityThread.java:5283)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by tpetmanson** [comment]
Sometimes the crash does not occur, but log shows things that might be related:

06-21 16:32:19.697  29813-29813/com.smilemeback E/com.smilemeback.activities.AddBaseActivity﹕ Source 'https:/lh5.googleusercontent.com/-_s0t5L2xVTU/UjDXUvl6ksI/AAAAAAAAAB4/nnZCE7bivs0/I/youtube_profile.jpg' does not exist

06-21 16:32:20.978  29813-29813/com.smilemeback E/ViewRootImpl﹕ sendUserActionEvent() mView == null

**Comment by tpetmanson** [comment]
Might be related to the issue: http://stackoverflow.com/questions/16221866/mediarecorder-failed-when-i-stop-the-recording

**Comment by tpetmanson** [comment]
One option is to replace mediarecorder with audiorecorder: http://stackoverflow.com/questions/19937740/why-is-mediarecorder-delaying-the-start-of-recording

**Comment by tpetmanson** [comment]
Replaced with issue https://github.com/SmileMeBack/smilemeback/issues/23

**Comment by tpetmanson** [comment]
fixed
