### ISSUE TITLE
Creating a new category FAILED

### ISSUE THREAD

**Issue by Renemes** [SmileMeBack/smilemeback#25]
Have added a picture, have given it a name. Pressing create category caused it to fail.

06-25 17:25:49.759  25514-25514/com.smilemeback D/AbsListView﹕ unregisterIRListener() is called
06-25 17:25:49.829  25514-25514/com.smilemeback D/dalvikvm﹕ GC_FOR_ALLOC freed 3870K, 71% free 14394K/48616K, paused 25ms, total 25ms
06-25 17:25:49.839  25514-25514/com.smilemeback I/dalvikvm-heap﹕ Grow heap (frag case) to 23.347MB for 8294416-byte allocation
06-25 17:25:49.879  25514-25523/com.smilemeback D/dalvikvm﹕ GC_FOR_ALLOC freed 564K, 55% free 21930K/48616K, paused 41ms, total 41ms
06-25 17:25:50.049  25514-25516/com.smilemeback E/dalvikvm﹕ adjustAdaptiveCoef max=4194304, min=1048576, ut=568
06-25 17:25:50.049  25514-25516/com.smilemeback D/dalvikvm﹕ GC_CONCURRENT freed 5K, 55% free 21925K/48616K, paused 7ms+2ms, total 174ms
06-25 17:25:50.049  25514-25514/com.smilemeback D/dalvikvm﹕ WAIT_FOR_CONCURRENT_GC blocked 18ms
06-25 17:25:50.049  25514-25514/com.smilemeback I/dalvikvm-heap﹕ Forcing collection of SoftReferences for 18662416-byte allocation
06-25 17:25:50.089  25514-25514/com.smilemeback E/dalvikvm﹕ adjustAdaptiveCoef max=6291456, min=1572864, ut=368
06-25 17:25:50.089  25514-25514/com.smilemeback D/dalvikvm﹕ GC_BEFORE_OOM freed 10K, 55% free 21914K/48616K, paused 37ms, total 37ms
06-25 17:25:50.089  25514-25514/com.smilemeback E/dalvikvm-heap﹕ Out of memory on a 18662416-byte allocation.
06-25 17:25:50.089  25514-25514/com.smilemeback I/dalvikvm﹕ "main" prio=5 tid=1 RUNNABLE
06-25 17:25:50.089  25514-25514/com.smilemeback I/dalvikvm﹕ | group="main" sCount=0 dsCount=0 obj=0x418829d0 self=0x41872670
06-25 17:25:50.089  25514-25514/com.smilemeback I/dalvikvm﹕ | sysTid=25514 nice=-19 sched=0/0 cgrp=apps handle=1075066332
06-25 17:25:50.089  25514-25514/com.smilemeback I/dalvikvm﹕ | state=R schedstat=( 0 0 0 ) utm=547 stm=130 core=1
06-25 17:25:50.089  25514-25514/com.smilemeback I/dalvikvm﹕ at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
06-25 17:25:50.099  25514-25514/com.smilemeback I/dalvikvm﹕ at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:596)
06-25 17:25:50.099  25514-25514/com.smilemeback I/dalvikvm﹕ at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
06-25 17:25:50.099  25514-25514/com.smilemeback I/dalvikvm﹕ at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:817)
06-25 17:25:50.099  25514-25514/com.smilemeback I/dalvikvm﹕ at android.content.res.Resources.loadDrawable(Resources.java:2854)
06-25 17:25:50.099  25514-25514/com.smilemeback I/dalvikvm﹕ at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
06-25 17:25:50.099  25514-25514/com.smilemeback I/dalvikvm﹕ at android.widget.ImageView.<init>(ImageView.java:126)
06-25 17:25:50.099  25514-25514/com.smilemeback I/dalvikvm﹕ at android.widget.ImageView.<init>(ImageView.java:116)
06-25 17:25:50.109  25514-25514/com.smilemeback I/dalvikvm﹕ at java.lang.reflect.Constructor.constructNative(Native Method)
06-25 17:25:50.109  25514-25514/com.smilemeback I/dalvikvm﹕ at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
06-25 17:25:50.109  25514-25514/com.smilemeback I/dalvikvm﹕ at android.view.LayoutInflater.createView(LayoutInflater.java:593)
06-25 17:25:50.109  25514-25514/com.smilemeback I/dalvikvm﹕ at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
06-25 17:25:50.109  25514-25514/com.smilemeback I/dalvikvm﹕ at android.view.LayoutInflater.onCreateView(LayoutInflater.java:666)
06-25 17:25:50.109  25514-25514/com.smilemeback I/dalvikvm﹕ at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:691)
06-25 17:25:50.109  25514-25514/com.smilemeback I/dalvikvm﹕ at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
06-25 17:25:50.109  25514-25514/com.smilemeback I/dalvikvm﹕ at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
06-25 17:25:50.109  25514-25514/com.smilemeback I/dalvikvm﹕ at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
06-25 17:25:50.119  25514-25514/com.smilemeback I/dalvikvm﹕ at com.smilemeback.views.IconView.inflateLayout(IconView.java:93)
06-25 17:25:50.119  25514-25514/com.smilemeback I/dalvikvm﹕ at com.smilemeback.views.IconView.initialize(IconView.java:71)
06-25 17:25:50.119  25514-25514/com.smilemeback I/dalvikvm﹕ at com.smilemeback.views.IconView.<init>(IconView.java:62)
06-25 17:25:50.119  25514-25514/com.smilemeback I/dalvikvm﹕ at com.smilemeback.adapters.BaseGridAdapter.getView(BaseGridAdapter.java:86)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.widget.AbsListView.obtainView(AbsListView.java:2586)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.widget.GridView.onMeasure(GridView.java:1045)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.view.View.measure(View.java:16419)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1034)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.widget.LinearLayout.onMeasure(LinearLayout.java:590)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.view.View.measure(View.java:16419)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:681)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.view.View.measure(View.java:16419)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.view.View.measure(View.java:16419)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.view.View.measure(View.java:16419)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2549)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.view.View.measure(View.java:16419)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2188)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1333)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1544)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1230)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5093)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.view.Choreographer.doCallbacks(Choreographer.java:591)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.view.Choreographer.doFrame(Choreographer.java:561)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.os.Handler.handleCallback(Handler.java:725)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.os.Handler.dispatchMessage(Handler.java:92)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.os.Looper.loop(Looper.java:137)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at android.app.ActivityThread.main(ActivityThread.java:5283)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at java.lang.reflect.Method.invokeNative(Native Method)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at java.lang.reflect.Method.invoke(Method.java:511)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ at dalvik.system.NativeStart.main(Native Method)
06-25 17:25:50.129  25514-25514/com.smilemeback I/dalvikvm﹕ [ 06-25 17:25:50.129 25514:25514 D/skia     ]
    --- allocation failed for scaled bitmap
06-25 17:25:50.129  25514-25514/com.smilemeback D/AndroidRuntime﹕ Shutting down VM
06-25 17:25:50.129  25514-25514/com.smilemeback W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41881960)
06-25 17:25:50.139  25514-25514/com.smilemeback E/AndroidRuntime﹕ FATAL EXCEPTION: main
    android.view.InflateException: Binary XML file line #10: Error inflating class <unknown>
            at android.view.LayoutInflater.createView(LayoutInflater.java:619)
            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:666)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:691)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at com.smilemeback.views.IconView.inflateLayout(IconView.java:93)
            at com.smilemeback.views.IconView.initialize(IconView.java:71)
            at com.smilemeback.views.IconView.<init>(IconView.java:62)
            at com.smilemeback.adapters.BaseGridAdapter.getView(BaseGridAdapter.java:86)
            at android.widget.AbsListView.obtainView(AbsListView.java:2586)
            at android.widget.GridView.onMeasure(GridView.java:1045)
            at android.view.View.measure(View.java:16419)
            at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1034)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:590)
            at android.view.View.measure(View.java:16419)
            at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:681)
            at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
            at android.view.View.measure(View.java:16419)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at android.view.View.measure(View.java:16419)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
            at android.view.View.measure(View.java:16419)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2549)
            at android.view.View.measure(View.java:16419)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2188)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1333)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1544)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1230)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5093)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
            at android.view.Choreographer.doCallbacks(Choreographer.java:591)
            at android.view.Choreographer.doFrame(Choreographer.java:561)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5283)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
            at android.view.LayoutInflater.createView(LayoutInflater.java:593)
            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:666)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:691)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at com.smilemeback.views.IconView.inflateLayout(IconView.java:93)
            at com.smilemeback.views.IconView.initialize(IconView.java:71)
            at com.smilemeback.views.IconView.<init>(IconView.java:62)
            at com.smilemeback.adapters.BaseGridAdapter.getView(BaseGridAdapter.java:86)
            at android.widget.AbsListView.obtainView(AbsListView.java:2586)
            at android.widget.GridView.onMeasure(GridView.java:1045)
            at android.view.View.measure(View.java:16419)
            at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1034)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:590)
            at android.view.View.measure(View.java:16419)
            at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:681)
            at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
            at android.view.View.measure(View.java:16419)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at android.view.View.measure(View.java:16419)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
            at android.view.View.measure(View.java:16419)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2549)
            at android.view.View.measure(View.java:16419)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2188)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1333)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1544)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1230)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5093)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
            at android.view.Choreographer.doCallbacks(Choreographer.java:591)
            at android.view.Choreographer.doFrame(Choreographer.java:561)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5283)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.OutOfMemoryError
            at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:596)
            at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
            at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:817)
            at android.content.res.Resources.loadDrawable(Resources.java:2854)
            at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
            at android.widget.ImageView.<init>(ImageView.java:126)
            at a

**Comment by tpetmanson** [comment]
unable to reproduce in current dev, so hopefully the problem fixed itself as we optimized the memory usage little bit
