### ISSUE TITLE
Deleting category ERROR

### ISSUE THREAD

**Issue by Renemes** [SmileMeBack/smilemeback#27]
I had two category items. When deleting one of them Everything seemed to be OK but when scrolling to make application display NOT deleted category items  app crashed.(other issue which wont display category items after deletion, unless you scroll the empty gallery first) 

06-25 17:36:55.826  27090-27090/com.smilemeback D/dalvikvm﹕ GC_FOR_ALLOC freed 3889K, 71% free 13871K/46464K, paused 44ms, total 44ms
06-25 17:36:55.836  27090-27090/com.smilemeback I/dalvikvm-heap﹕ Grow heap (frag case) to 22.836MB for 8294416-byte allocation
06-25 17:36:55.857  27090-27099/com.smilemeback D/dalvikvm﹕ GC_FOR_ALLOC freed 48K, 53% free 21923K/46464K, paused 24ms, total 24ms
06-25 17:36:55.907  27090-27092/com.smilemeback E/dalvikvm﹕ adjustAdaptiveCoef max=4194304, min=1048576, ut=568
06-25 17:36:55.907  27090-27092/com.smilemeback D/dalvikvm﹕ GC_CONCURRENT freed 72K, 53% free 21851K/46464K, paused 6ms+3ms, total 49ms
06-25 17:36:56.147  27090-27090/com.smilemeback E/dalvikvm﹕ adjustAdaptiveCoef max=6291456, min=1572864, ut=368
06-25 17:36:56.147  27090-27090/com.smilemeback D/dalvikvm﹕ GC_FOR_ALLOC freed <1K, 53% free 21851K/46464K, paused 22ms, total 22ms
06-25 17:36:56.147  27090-27090/com.smilemeback I/dalvikvm-heap﹕ Forcing collection of SoftReferences for 18662416-byte allocation
06-25 17:36:56.177  27090-27090/com.smilemeback E/dalvikvm﹕ adjustAdaptiveCoef max=8388608, min=2097152, ut=256
06-25 17:36:56.177  27090-27090/com.smilemeback D/dalvikvm﹕ GC_BEFORE_OOM freed 10K, 53% free 21840K/46464K, paused 37ms, total 37ms
06-25 17:36:56.177  27090-27090/com.smilemeback E/dalvikvm-heap﹕ Out of memory on a 18662416-byte allocation.
06-25 17:36:56.177  27090-27090/com.smilemeback I/dalvikvm﹕ "main" prio=5 tid=1 RUNNABLE
06-25 17:36:56.177  27090-27090/com.smilemeback I/dalvikvm﹕ | group="main" sCount=0 dsCount=0 obj=0x418829d0 self=0x41872670
06-25 17:36:56.177  27090-27090/com.smilemeback I/dalvikvm﹕ | sysTid=27090 nice=0 sched=0/0 cgrp=apps handle=1075066332
06-25 17:36:56.187  27090-27090/com.smilemeback I/dalvikvm﹕ | state=R schedstat=( 0 0 0 ) utm=922 stm=176 core=0
06-25 17:36:56.187  27090-27090/com.smilemeback I/dalvikvm﹕ at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
06-25 17:36:56.187  27090-27090/com.smilemeback I/dalvikvm﹕ at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:596)
06-25 17:36:56.187  27090-27090/com.smilemeback I/dalvikvm﹕ at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
06-25 17:36:56.197  27090-27090/com.smilemeback I/dalvikvm﹕ at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:817)
06-25 17:36:56.197  27090-27090/com.smilemeback I/dalvikvm﹕ at android.content.res.Resources.loadDrawable(Resources.java:2854)
06-25 17:36:56.197  27090-27090/com.smilemeback I/dalvikvm﹕ at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
06-25 17:36:56.207  27090-27090/com.smilemeback I/dalvikvm﹕ at android.widget.ImageView.<init>(ImageView.java:126)
06-25 17:36:56.207  27090-27090/com.smilemeback I/dalvikvm﹕ at android.widget.ImageView.<init>(ImageView.java:116)
06-25 17:36:56.207  27090-27090/com.smilemeback I/dalvikvm﹕ at java.lang.reflect.Constructor.constructNative(Native Method)
06-25 17:36:56.207  27090-27090/com.smilemeback I/dalvikvm﹕ at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
06-25 17:36:56.217  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.LayoutInflater.createView(LayoutInflater.java:593)
06-25 17:36:56.237  27090-27090/com.smilemeback I/dalvikvm﹕ at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
06-25 17:36:56.237  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.LayoutInflater.onCreateView(LayoutInflater.java:666)
06-25 17:36:56.237  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:691)
06-25 17:36:56.237  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
06-25 17:36:56.237  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
06-25 17:36:56.237  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
06-25 17:36:56.247  27090-27090/com.smilemeback I/dalvikvm﹕ at com.smilemeback.views.IconView.inflateLayout(IconView.java:93)
06-25 17:36:56.257  27090-27090/com.smilemeback I/dalvikvm﹕ at com.smilemeback.views.IconView.initialize(IconView.java:71)
06-25 17:36:56.257  27090-27090/com.smilemeback I/dalvikvm﹕ at com.smilemeback.views.IconView.<init>(IconView.java:62)
06-25 17:36:56.267  27090-27090/com.smilemeback I/dalvikvm﹕ at com.smilemeback.adapters.BaseGridAdapter.getView(BaseGridAdapter.java:86)
06-25 17:36:56.267  27090-27090/com.smilemeback I/dalvikvm﹕ at android.widget.AbsListView.obtainView(AbsListView.java:2586)
06-25 17:36:56.277  27090-27090/com.smilemeback I/dalvikvm﹕ at android.widget.GridView.makeAndAddView(GridView.java:1346)
06-25 17:36:56.277  27090-27090/com.smilemeback I/dalvikvm﹕ at android.widget.GridView.makeRow(GridView.java:341)
06-25 17:36:56.277  27090-27090/com.smilemeback I/dalvikvm﹕ at android.widget.GridView.fillDown(GridView.java:283)
06-25 17:36:56.277  27090-27090/com.smilemeback I/dalvikvm﹕ at android.widget.GridView.fillFromTop(GridView.java:417)
06-25 17:36:56.277  27090-27090/com.smilemeback I/dalvikvm﹕ at android.widget.GridView.layoutChildren(GridView.java:1234)
06-25 17:36:56.277  27090-27090/com.smilemeback I/dalvikvm﹕ at android.widget.AbsListView.onTouchEvent(AbsListView.java:4389)
06-25 17:36:56.287  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.View.dispatchTouchEvent(View.java:7668)
06-25 17:36:56.287  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2395)
06-25 17:36:56.287  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
06-25 17:36:56.287  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
06-25 17:36:56.287  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
06-25 17:36:56.287  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
06-25 17:36:56.287  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
06-25 17:36:56.287  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
06-25 17:36:56.287  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
06-25 17:36:56.297  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
06-25 17:36:56.297  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
06-25 17:36:56.297  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
06-25 17:36:56.297  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
06-25 17:36:56.297  27090-27090/com.smilemeback I/dalvikvm﹕ at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2284)
06-25 17:36:56.297  27090-27090/com.smilemeback I/dalvikvm﹕ at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1578)
06-25 17:36:56.297  27090-27090/com.smilemeback I/dalvikvm﹕ at android.app.Activity.dispatchTouchEvent(Activity.java:2468)
06-25 17:36:56.297  27090-27090/com.smilemeback I/dalvikvm﹕ at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2232)
06-25 17:36:56.297  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.View.dispatchPointerEvent(View.java:7875)
06-25 17:36:56.297  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3898)
06-25 17:36:56.297  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3782)
06-25 17:36:56.297  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5034)
06-25 17:36:56.297  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5013)
06-25 17:36:56.297  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5111)
06-25 17:36:56.307  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
06-25 17:36:56.307  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
06-25 17:36:56.307  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:174)
06-25 17:36:56.307  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5084)
06-25 17:36:56.307  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5130)
06-25 17:36:56.307  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
06-25 17:36:56.307  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.Choreographer.doCallbacks(Choreographer.java:591)
06-25 17:36:56.307  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.Choreographer.doFrame(Choreographer.java:559)
06-25 17:36:56.307  27090-27090/com.smilemeback I/dalvikvm﹕ at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
06-25 17:36:56.307  27090-27090/com.smilemeback I/dalvikvm﹕ at android.os.Handler.handleCallback(Handler.java:725)
06-25 17:36:56.307  27090-27090/com.smilemeback I/dalvikvm﹕ at android.os.Handler.dispatchMessage(Handler.java:92)
06-25 17:36:56.307  27090-27090/com.smilemeback I/dalvikvm﹕ at android.os.Looper.loop(Looper.java:137)
06-25 17:36:56.307  27090-27090/com.smilemeback I/dalvikvm﹕ at android.app.ActivityThread.main(ActivityThread.java:5283)
06-25 17:36:56.307  27090-27090/com.smilemeback I/dalvikvm﹕ at java.lang.reflect.Method.invokeNative(Native Method)
06-25 17:36:56.307  27090-27090/com.smilemeback I/dalvikvm﹕ at java.lang.reflect.Method.invoke(Method.java:511)
06-25 17:36:56.307  27090-27090/com.smilemeback I/dalvikvm﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
06-25 17:36:56.307  27090-27090/com.smilemeback I/dalvikvm﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
06-25 17:36:56.307  27090-27090/com.smilemeback I/dalvikvm﹕ at dalvik.system.NativeStart.main(Native Method)
06-25 17:36:56.307  27090-27090/com.smilemeback I/dalvikvm﹕ [ 06-25 17:36:56.307 27090:27090 D/skia     ]
    --- allocation failed for scaled bitmap
06-25 17:36:56.307  27090-27090/com.smilemeback E/InputEventReceiver﹕ Exception dispatching input event.
06-25 17:36:56.307  27090-27090/com.smilemeback D/AndroidRuntime﹕ Shutting down VM
06-25 17:36:56.307  27090-27090/com.smilemeback W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41881960)
06-25 17:36:56.327  27090-27090/com.smilemeback E/AndroidRuntime﹕ FATAL EXCEPTION: main
    android.view.InflateException: Binary XML file line #10: Error inflating class <unknown>
            at android.view.LayoutInflater.createView(LayoutInflater.java:619)
            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:666)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:691)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at com.smilemeback.views.IconView.inflateLayout(IconView.java:93)
            at com.smilemeback.views.IconView.initialize(IconView.java:71)
            at com.smilemeback.views.IconView.<init>(IconView.java:62)
            at com.smilemeback.adapters.BaseGridAdapter.getView(BaseGridAdapter.java:86)
            at android.widget.AbsListView.obtainView(AbsListView.java:2586)
            at android.widget.GridView.makeAndAddView(GridView.java:1346)
            at android.widget.GridView.makeRow(GridView.java:341)
            at android.widget.GridView.fillDown(GridView.java:283)
            at android.widget.GridView.fillFromTop(GridView.java:417)
            at android.widget.GridView.layoutChildren(GridView.java:1234)
            at android.widget.AbsListView.onTouchEvent(AbsListView.java:4389)
            at android.view.View.dispatchTouchEvent(View.java:7668)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2395)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2284)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1578)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2468)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2232)
            at android.view.View.dispatchPointerEvent(View.java:7875)
            at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3898)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3782)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5034)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5013)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5111)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
            at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
            at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:174)
            at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5084)
            at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5130)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
            at android.view.Choreographer.doCallbacks(Choreographer.java:591)
            at android.view.Choreographer.doFrame(Choreographer.java:559)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5283)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect

**Comment by tpetmanson** [comment]
unable to reproduce in current dev, so hopefully the problem fixed itself as we optimized the memory usage little bit
