### ISSUE TITLE
Application crashed when returning from AddCategory

### ISSUE THREAD

**Issue by tpetmanson** [SmileMeBack/smilemeback#6]
06-17 21:05:29.310  13776-13776/com.smilemeback E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent {  }} to activity {com.smilemeback/com.smilemeback.activities.CategoriesActivity}: java.lang.NullPointerException
            at android.app.ActivityThread.deliverResults(ActivityThread.java:2980)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3023)
            at android.app.ActivityThread.access$1100(ActivityThread.java:123)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1177)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4424)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at java.util.regex.Matcher.reset(Matcher.java:181)
            at java.util.regex.Matcher.<init>(Matcher.java:94)
            at java.util.regex.Pattern.matcher(Pattern.java:290)
            at com.smilemeback.storage.Name.<init>(Name.java:39)
            at com.smilemeback.activities.CategoriesActivity.onActivityResult(CategoriesActivity.java:184)
            at android.app.Activity.dispatchActivityResult(Activity.java:4649)
            at android.app.ActivityThread.deliverResults(ActivityThread.java:2976)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3023)
            at android.app.ActivityThread.access$1100(ActivityThread.java:123)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1177)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4424)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
            at dalvik.system.NativeStart.main(Native Method)
06-17 21:05:29.360  13776-13778/com.smilemeback D/dalvikvm﹕ GC_CONCURRENT freed 2484K, 64% free 15129K/41863K, paused 2ms+4ms
06-17 21:05:30.900  13776-13776/com.smilemeback I/Process﹕ Sending signal. PID: 13776 SIG: 9

**Comment by tpetmanson** [comment]
Issue occurred when user pressed "back" in AddCategoryActivity or AddIconActivity. When handling the response, the code always assumed that the user completed all the steps.
